{% set PKG_NAME = 'arduino-rpc' %}
{% set LIB_NAME = 'ArduinoRpc' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}

{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

requirements:
  build:
    - arduino-helpers >=0.4
    - arduino-memory >=0.2
    - c-array-defs >=0.2
    - clang-helpers >=0.3
    - future
    - jinja2
    - nadamq >=0.10
    - nanopb-helpers >=0.5
    - pandas >=0.15
    - path_helpers >=0.2
    - paver
    - pip
    - platformio-helpers
    #: .. versionchanged:: 1.11
    - python {{ python }}
    - serial-device >=0.2
    #: .. versionadded:: 1.11
    - six

  run:
    - arduino-helpers >=0.4
    - arduino-memory >=0.2
    - c-array-defs >=0.2
    - clang-helpers >=0.3
    - jinja2
    - nadamq >=0.10
    - nanopb-helpers >=0.5
    - pandas >=0.15
    - path_helpers >=0.2
    #: .. versionchanged:: 1.11
    - python {{ python }}
    - serial-device >=0.2
    #: .. versionadded:: 1.11
    - six

build:
  script:
    # Generate Arduino `library.properties` file
    - python -m paver generate_arduino_library_properties
    # Copy Arduino library to Conda include directory
    - python -c
        "import os.path; import os; import shutil; import platformio_helpers as pioh;
        lib_src_dir = os.path.join(os.environ['SRC_DIR'], '{{ MODULE_NAME }}',
                                   'Arduino', 'library', '{{ LIB_NAME }}');
        install_dir = pioh.conda_arduino_include_path().joinpath('{{ LIB_NAME }}');
        shutil.copytree(lib_src_dir, install_dir);
        "
    # Generate `setup.py` from `pavement.py` definition.
    - python -m paver generate_setup
    # Install source directory as Python package.
    - python -B setup.py install --single-version-externally-managed --record record.txt

about:
  home: https://github.com/sci-bots/arduino-rpc
  license: MIT
