{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: arduino-rpc
  version: {{ GIT_VERSION }}

requirements:
  build:
    - arduino-helpers >=0.4
    - arduino-memory >=0.2
    - c-array-defs >=0.2
    - clang-helpers >=0.3
    - future
    - jinja2
    - nadamq >=0.10
    - nanopb-helpers >=0.5
    - pandas >=0.15
    - path_helpers >=0.2
    - paver
    - pip
    - python 2.7*
    - serial-device >=0.2
    #: .. versionadded:: X.X.X
    - six

  run:
    - arduino-helpers >=0.4
    - arduino-memory >=0.2
    - c-array-defs >=0.2
    - clang-helpers >=0.3
    - jinja2
    - nadamq >=0.10
    - nanopb-helpers >=0.5
    - pandas >=0.15
    - path_helpers >=0.2
    - serial-device >=0.2
    #: .. versionadded:: X.X.X
    - six

about:
  home: https://github.com/sci-bots/arduino-rpc
  license: MIT
