{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
{% set PKG_NAME = 'arduino-rpc' %}
{% set LIB_NAME = 'ArduinoRpc' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}
package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

requirements:
  build:
    - python >=3.6
    - jinja2
    - nadamq
    - pandas
    - numpy
    - protobuf
    - serial-device
    - platformio
    - dropbot-headers
    - path-helpers
    - clang-helpers
    - nanopb-helpers
    - arduino-helpers
    - platformio-helpers

build:
  # If this is a new build for the same version, increment the build number.
  # If you do not include this key, it defaults to 0.
  number: 0
  noarch: python
  script:
    # Copy Arduino library to Conda include directory and generate Arduino `library.properties` file
    - python file_handler.py {{ SRC_DIR }} {{ PREFIX }} {{ PKG_NAME }} {{ MODULE_NAME }} {{ LIB_NAME }}
    # Run setup
    - python setup.py install --single-version-externally-managed --record record.txt

outputs:
  - name: {{ PKG_NAME }}-dev
    noarch: generic
    files:
      - share
    requirements:
      run:
        - platformio
        - dropbot-headers

  - name: {{ PKG_NAME }}
    noarch: python
    files:
      - {{ SP_DIR }}/{{ MODULE_NAME }}
    requirements:
      run:
        - python >=3.6
        - {{ pin_compatible(PKG_NAME + '-dev', max_pin='x.x') }}
        - jinja2
        - nadamq
        - pandas
        - numpy
        - protobuf
        - serial-device
        - platformio
        - path-helpers
        - clang-helpers
        - nanopb-helpers
        - arduino-helpers
        - platformio-helpers

test:
  imports:
    - {{ MODULE_NAME }}

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: MIT
  summary: Code generation for memory-efficient remote-procedure-calls between a host CPU (Python) and a device (C++) (e.g., Arduino).

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
#  git_url: ../
  path: ..
