{% set PKG_NAME = 'arduino-rpc' %}
{% set LIB_NAME = 'ArduinoRpc' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}

{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

requirements:
  build:
    - arduino-helpers >=0.7
    - arduino-memory >=1.4
    - c-array-defs >=1.3
    #: .. versionchanged:: X.X.X
    - clang-helpers >=0.8
    - future
    - jinja2
    - nadamq >=0.19
    - nanopb-helpers >=0.12
    - pandas >=0.15
    - path_helpers >=0.7
    - paver
    - pip
    - platformio-helpers >=0.8
    #: .. versionchanged:: 1.11
    - python
    - serial-device >=0.11
    #: .. versionadded:: 1.11
    - six

build:
  noarch: python
  script:
    # Generate Arduino `library.properties` file
    - python -m paver generate_arduino_library_properties
    # Copy Arduino library to Conda include directory
    - python -c
        "import os.path; import os; import shutil; import platformio_helpers as pioh;
        lib_src_dir = os.path.join(os.environ['SRC_DIR'], '{{ MODULE_NAME }}',
                                   'Arduino', 'library', '{{ LIB_NAME }}');
        install_dir = pioh.conda_arduino_include_path().joinpath('{{ LIB_NAME }}');
        shutil.copytree(lib_src_dir, install_dir);
        "
    # Generate `setup.py` from `pavement.py` definition.
    - python -m paver generate_setup
    # Install source directory as Python package.
    - python -B setup.py install --single-version-externally-managed --record record.txt

outputs:
  - name: {{ PKG_NAME }}-dev
    noarch: generic
    files:
      - share
  - name: {{ PKG_NAME }}
    noarch: python
    files:
      - Lib/site-packages/{{ MODULE_NAME }}
    requirements:
      run:
        - {{ pin_compatible(PKG_NAME + '-dev', max_pin='x.x') }}
        - arduino-helpers >=0.7
        - arduino-memory >=1.4
        - c-array-defs >=1.3
        #: .. versionchanged:: X.X.X
        - clang-helpers >=0.8
        - jinja2
        - nadamq >=0.19
        - nanopb-helpers >=0.12
        - pandas >=0.15
        - path_helpers >=0.7
        #: .. versionchanged:: 1.11
        - python
        - serial-device >=0.11
        #: .. versionadded:: 1.11
        - six

about:
  home: https://github.com/sci-bots/arduino-rpc
  license: MIT
